services:
  database:
    image: 'postgres:15.2'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=educational-db'
      - 'POSTGRES_PASSWORD=1234'
